### ISSUE TITLE
suggestions to singularity preflight 

### ISSUE THREAD

**Issue by Phuong-Le** [sanger-bentley-group/gps-pipeline#100]
https://github.com/sanger-bentley-group/gps-pipeline/blob/fcbcece2c278fa56792850a68f1325f6c6246089/main.nf#L32

@HarryHung thanks very much for sharing your code. A good idea to predownload images prior to running workflows. 

Here, it seems that you're searching the first config file for a 'container' flag. However, if someone else were to adopt this and run with multiple config files, this would be quite unstable. 

Nextflow seems to have the `workflow.container` variable that would be useful in this case?

Better still, I think the preflight code deserves its own git repo, so you can use it in multiple pipelines with something like a `git submodule`. Would this be something you're interested in? Let's discuss this further?

**Comment by Phuong-Le** [comment]
ah okay I didn't know `workflow.container` wasn't working back in the day, and yeah can confirm `workflow.container` is working as I tested it before submitting the issue.

Definitely keep me posted - thanks for suggesting `git subtree`

**Comment by HarryHung** [comment]
@Phuong-Le I have done the above-mentioned tasks in this branch:
https://github.com/sanger-bentley-group/gps-pipeline/tree/feature/use-workflow-container-introspection
commits:
https://github.com/sanger-bentley-group/gps-pipeline/compare/master...feature/use-workflow-container-introspection

Are these changes what you were looking for?

**Comment by HarryHung** [comment]
@Phuong-Le 

Fixed.

If I extract the `singularityPreflight` function into another repository, I will create another ticket for it.
