### ISSUE TITLE
set max number of threads

### ISSUE THREAD

**Issue by juanjo255** [sanger-bentley-group/gps-pipeline#122]
Hello developers!

I would like to know if it is possible to set a maximum number of threads to use, I would like not to use all of the available. I know there is an option to limit assembler threads, but I would like to limit every process that have multi-threading.

I hope you can help me,

Thank you,

Juan

**Comment by HarryHung** [comment]
Hi Juan,

Unforunately, we do not have that setting as a part of the pipeline. 

If you are using Docker as the container engine, you can consider using Docker's [resource constraints](https://docs.docker.com/engine/containers/resource_constraints/), as the pipeline run all processes in containers. Restricting CPUs  count that Docker is allowed to assign to each container will effectively restrict the maximum number of threads to use for each process. 

One possible approach is modifying your local copy of `gps-pipeline/nextflow.config` at this line 
https://github.com/sanger-bentley-group/gps-pipeline/blob/fb9fd410344f2776c21088945437ccd314193ce9/nextflow.config#L126
For example, you can add the option `--cpus=<value>` to set Docker only allocate certain number of CPUs to each container. 

---

[Similar thing can be done if you are using Singularity](https://docs.sylabs.io/guides/main/user-guide/cli/singularity_exec.html) as well. One approach is adding one more line to your local copy of `gps-pipeline/nextflow.config` within this code block
https://github.com/sanger-bentley-group/gps-pipeline/blob/fb9fd410344f2776c21088945437ccd314193ce9/nextflow.config#L135-L139
Add the line: `runOptions = '--cpus <valule>`' to set the number of CPUs available to each container (do not just add the content to Line 126 stated for Docker above, that part of config only applies to Docker).

I hope it helps!

Harry
